import { BadgeCheck, Sparkle, Zap } from "lucide-react";

export const plans = [
  {
    key: "free",
    title: "Free",
    icon: <Sparkle className="text-primary h-6 w-6" />,
    description: "Perfect for casual users & explorers",
    price: "₹0 /mo",
    subNote: "Unlimited usage for 1st month — no limits, all features unlocked!",
    features: [
      "3 Enhances/day",
      "5 Prompt tests/day",
      "Access to 2 AI models",
      "Up to 10 saved prompts",
      "2 prompt folders",
      "Limited prompt history",
      "100K tokens/month included",
      "Community support",
    ],
    cta: "Start Free",
    highlight: false,
  },
  {
    key: "premium",
    title: "Pro",
    icon: <Zap className="h-6 w-6 text-yellow-500" />,
    description: "For prompt engineers & AI power users",
    price: "₹999 /mo (~$12)",
    features: [
      "Everything in Free",
      "Unlimited Enhances & Prompt Tests",
      "Access to all AI models (GPT, Claude, Gemini, etc.)",
      "Up to 1,000 saved prompts",
      "Extended usage limits ~5M tokens/month",
      "Unlimited folders & versions",
      "Priority email support",
      "Full prompt history access",
    ],
    cta: "Upgrade Now",
    highlight: true,
  },
  {
    key: "enterprise",
    title: "Enterprise",
    icon: <BadgeCheck className="h-6 w-6 text-green-600" />,
    description: "Best for professionals, teams & yearly savers",
    price: "₹9,999 /yr (~$120)",
    features: [
      "Everything in Pro",
      "2 months free (₹2,000 off)",
      "Early access to new features",
      "Unlimited Saved Prompts",
      "Extended usage limits ~25M tokens/month",
      "Annual billing convenience",
      "Onboarding support (coming soon)",
    ],
    cta: "Go Yearly",
    highlight: false,
  },
];
